- name: Create skhd config directory
  ansible.builtin.file:
    path: ~/.config/skhd
    state: directory
    mode: '0755'

- name: Install skhd
  community.general.homebrew:
    name:
      - koekeishiya/formulae/skhd
    state: present

- name: Copy skhd config
  ansible.builtin.copy:
    src: "{{ ansible_env.PWD }}/roles/wm/files/skhdrc"
    dest: ~/.config/skhd/skhdrc

- name: Start brew service skhd
  ansible.builtin.command:
    cmd: /usr/local/bin/brew services stop skhd
  when: ansible_os_family == "Darwin"

