- name: Install php
  community.general.homebrew:
    name:
      - php@7.4
      - yarn
      - composer
      - phpstan
      - phpunit
      - php-cs-fixer
      - python3
      - pkg-config
      - imagemagick
    state: present

- name: Install virtualbox
  community.general.homebrew_cask:
    name:
      - virtualbox
    state: present

- name: Install vagrant
  community.general.homebrew_cask:
    name:
      - vagrant
    state: present

- name: Install xdebug
  community.general.pear:
    name: pecl/xdebug
    state: present

- name: Stat symfony-cli
  stat:
    path: /usr/local/bin/symfony
  register: symfony

- name: Download symfony-cli
  ansible.builtin.get_url:
    url: https://get.symfony.com/cli/installer
    dest: /tmp/symfony-installer
  when: symfony.stat.exists == False

- name: Install symfony-cli
  ansible.builtin.command:
    cmd: bash /tmp/symfony-installer
  when: symfony.stat.exists == False


- name: Copy to system location
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/.symfony/bin/symfony"
    dest: "/usr/local/bin/symfony"
    owner: kreemer
    group: admin
    mode: '0755'
  when: symfony.stat.exists == False

    
- name: Install phpstorm
  community.general.homebrew_cask:
    name:
      - phpstorm
    state: present


- name: Install docker 
  community.general.homebrew_cask:
    name:
      - docker
    state: present
