- name: Install neovim
  community.general.homebrew:
    name:
      - neovim
    state: present

- name: Checkout awesome vimrc
  ansible.builtin.git:
    repo: 'https://github.com/amix/vimrc.git'
    dest: ~/.vim_runtime
    depth: 1

- name: Install awesome vimrc
  ansible.builtin.command:
    cmd: sh ~/.vim_runtime/install_awesome_vimrc.sh
    creates: ~/.vimrc

- name: Install vimrc config
  ansible.builtin.template:
    src: my_configs.vim.j2
    dest: ~/.vim_runtime/my_configs.vim
    owner: "{{ lookup('env', 'USER') }}"
    group: staff
    mode: '0644'
    backup: yes
