- name: Install neovim
  community.general.homebrew:
    name:
      - neovim
    state: present

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory
    mode: '0755'

- name: Copy files
  ansible.builtin.copy:
    src: "{{ ansible_env.PWD }}/roles/nvim/files/"
    dest: ~/.config/nvim/


- name: Install vimplug
  ansible.builtin.shell:
    cmd: sh -c 'curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'


- name: Install intelephense lsp
  ansible.builtin.shell:
    cmd: npm install -g intelephense




