- name: Get mac config
  ansible.builtin.include_vars:
    file: "config.yml"
    name: config

- name: Apply configs
  ansible.builtin.include_tasks:
    file: apply.yml
  loop: "{{ config.root }}"

- name: Restart Finder 
  ansible.builtin.command:
    cmd: killall Dock && killall Finder

- name: Install mas
  community.general.homebrew:
    name:
      - mas
    state: present

- name: Install vimari
  community.general.mas:
    id: 
      - 1480933944
      
