root:
#  - description: "Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window"
#    domain: /Library/Preferences/com.apple.loginwindow
#    key: AdminHostInfo
#    type: string
#    value: HostName

  - description: Increase window resize speed for Cocoa applications
    domain: NSGlobalDomain
    key: NSWindowResizeTime
    type: float
    value: 0.001

  - description: Save to disk (not to iCloud) by default
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

  - description: Automatically quit printer app once the print jobs complete
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true

  - description: Disable Resume system-wide
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false

  - description: Disable automatic termination of inactive apps
    domain: NSGlobalDomain
    key: NSDisableAutomaticTermination
    type: bool
    value: true

  - description: Disable automatic capitalization as it’s annoying when typing code
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false

  - description: Disable smart dashes as they’re annoying when typing code
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false

  - description: Disable automatic period substitution as it’s annoying when typing code
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false

  - description: Disable smart quotes as they’re annoying when typing code
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false

  - description: Disable auto-correct
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

  ###############################################################################
  # Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
  ###############################################################################

  - description: enable tap to click for this user and for the login screen
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1

  - description: enable tap to click for this user and for the login screen
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

  - description: enable tap to click for this user and for the login screen
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1

  - description: Use scroll gesture with the Ctrl (^) modifier key to zoom
    domain: com.apple.universalaccess
    key: closeViewScrollWheelToggle
    type: bool
    value: true

  - description: Disable auto-correct
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

  - description: Disable natural scroll
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false

  ###############################################################################
  # Energy saving                                                               #
  ###############################################################################

  - description: Require password immediately after sleep or screen saver begins
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1

  - description: Require password immediately after sleep or screen saver begins
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0

  ###############################################################################
  # Finder                                                                      #
  ###############################################################################


  - description: show all filename extensions
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

  - description: Disable the warning when changing a file extension
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

  - description: Disable the warning before emptying the Trash
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

  - description: disable window animations and Get Info animations
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true

  - description: When performing a search, search the current folder by default
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

  - description: Avoid creating .DS_Store files on network or USB volumes
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

  - description: Avoid creating .DS_Store files on network or USB volumes
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

  # Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
  - description: Use list view in all Finder windows by default.
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"

  ###############################################################################
  # Dock, Dashboard, and hot corners                                            #
  ###############################################################################

  - description: Minimize windows into their application’s icon
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true

  - description: Hide indicator lights for open applications in the Dock
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true

  - description: Speed up Mission Control animations
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1

  - description: Disable Dashboard
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true

  - description: Don’t show Dashboard as a Space
    domain: com.apple.dock
    key: dashboard-in-overlay
    type: bool
    value: true

  - description: Don’t automatically rearrange Spaces based on most recent use
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

  - description: Don’t show recent applications in Dock
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false


  ###############################################################################
  # Safari & WebKit                                                             #
  ###############################################################################

  - description: don’t send search queries to Apple
    domain: com.apple.Safari
    key: UniversalSearchEnabled
    type: bool
    value: false

  - description: don’t send search queries to Apple
    domain: com.apple.Safari
    key: SuppressSearchSuggestions
    type: bool
    value: true

  - description: Set Safari’s home page to `about:blank` for faster loading
    domain: com.apple.Safari
    key: HomePage
    type: string
    value: "about:blank"

  - description: Prevent Safari from opening ‘safe’ files automatically after downloading
    domain: com.apple.Safari
    key: AutoOpenSafeDownloads
    type: bool
    value: false

  - description: Hide Safari’s bookmarks bar by default
    domain: com.apple.Safari
    key: ShowFavoritesBar
    type: bool
    value: false

  - description: Disable Safari’s thumbnail cache for History and Top Sites
    domain: com.apple.Safari
    key: DebugSnapshotsUpdatePolicy
    type: int
    value: 2

  - description: Disable continuous spellchecking
    domain: com.apple.Safari
    key: WebContinuousSpellCheckingEnabled
    type: bool
    value: false

  - description: Disable auto-correct
    domain: com.apple.Safari
    key: WebAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

  - description: Enable the Develop menu and the Web Inspector in Safari
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true

  - description: Enable the Develop menu and the Web Inspector in Safari
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true

  - description: Enable the Develop menu and the Web Inspector in Safari
    domain: com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
    type: bool
    value: true

  - description: Disable AutoFill
    domain: com.apple.Safari
    key: AutoFillFromAddressBook
    type: bool
    value: false


  - description: Disable AutoFill
    domain: com.apple.Safari
    key: AutoFillPasswords
    type: bool
    value: false

  - description: Disable AutoFill
    domain: com.apple.Safari
    key: AutoFillCreditCardData
    type: bool
    value: false

  - description: Disable AutoFill
    domain: com.apple.Safari
    key: AutoFillMiscellaneousForms
    type: bool
    value: false

  ###############################################################################
  # Mail                                                                        #
  ###############################################################################

  - description: Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
    domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: false

  ###############################################################################
  # Spotlight                                                                    #
  ###############################################################################

  ###############################################################################
  # Terminal                                                                    #
  ###############################################################################

  - description: Disable secure keyboard
    domain: com.apple.terminal
    key: SecureKeyboardEntry
    type: bool
    value: false

  - description: Disable the annoying line marks
    domain: com.apple.Terminal
    key: ShowLineMarks
    type: int
    value: 0

  ###############################################################################
  # Time Machine                                                                #
  ###############################################################################

  - description: Prevent Time Machine from prompting to use new hard drives as backup volume
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true

  ###############################################################################
  # Activity Monitor                                                            #
  ###############################################################################

  - description: Show the main window when launching Activity Monitor
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true

  - description: Visualize CPU usage in the Activity Monitor Dock icon
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5

  - description: Show all processes in Activity Monitor
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0

  - description: Sort Activity Monitor results by CPU usage
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"

  - description: Sort Activity Monitor results by CPU usage
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0

  ###############################################################################
  # Mac App Store                                                               #
  ###############################################################################

  - description: Enable the automatic update check
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: true

  - description: Check for software updates daily, not just once per week
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1

  - description: Download newly available updates in background
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: int
    value: 1

  - description: Install System data files & security updates
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: int
    value: 1

  - description: Automatically download apps purchased on other Macs
    domain: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    type: int
    value: 1

  - description: Turn on app auto-update
    domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: true

  ###############################################################################
  # Photos                                                                      #
  ###############################################################################

  - description: Prevent Photos from opening automatically when devices are plugged in
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: true

  ###############################################################################
  # Messages                                                                    #
  ###############################################################################

  ###############################################################################
  # Menu Bar                                                                    #
  ###############################################################################
  - description: Do not autohide menu bar
    domain: NSGlobalDomain
    key: _HIHideMenuBar
    type: bool
    value: false 

  
