- name: Install git
  community.general.homebrew:
    name:
      - git
      - diff-so-fancy
      - git-lfs
    state: present

- name: Install git-lfs
  ansible.builtin.command: git lfs install

- name: Install gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    owner: "{{ lookup('env', 'USER') }}"
    group: staff
    mode: '0644'
    backup: yes

- name: Install gitignore
  ansible.builtin.template:
    src: gitignore.j2
    dest: ~/.gitignore
    owner: "{{ lookup('env', 'USER') }}"
    group: staff
    mode: '0644'
    backup: yes

- name: Create Developer directory
  ansible.builtin.file:
    path: ~/Code
    state: directory
    mode: '0755'

- name: Create Developer/work directory
  ansible.builtin.file:
    path: ~/Code/UB
    state: directory
    mode: '0755'

- name: Create Developer/personal directory
  ansible.builtin.file:
    path: ~/Code/kreemer
    state: directory
    mode: '0755'

- name: Install gh
  community.general.homebrew:
    name:
      - gh
    state: present
